apiVersion: v1
appVersion: "20.10.1"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: >
  SRS enodeb
home: https://github.com/Gradiant/charts
sources:
  - https://github.com/srsLTE/srsLTE
icon: https://pbs.twimg.com/profile_images/1153713220127006724/KfcRHyU-_400x400.jpg
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
name: srs-enb
version: 0.1.1
keywords:
  - lte
  - enodeb
