# Default values for open5gs-abac.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imageRegistry: ""
  imagePullSecrets: []  # E.g. imagePullSecrets: - myRegistryKeySecretName
  storageClass: ""

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

customOpen5gsConfig: {}

serviceAccount:
  create: false
  name: abac-service-account
  annotations: {}
  automountServiceAccountToken: true

podAnnotations: {}
podLabels: {}

podAntiAffinityPreset: soft

schedulerName: ""

priorityClassName: ""

hostAliases: []

initContainers: []

command: []
args: []

extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""

lifecycleHooks: {}
customStartupProbe: {}
customLivenessProbe: {}
customReadinessProbe: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 600
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1

topologySpreadConstraints: []

podSecurityContext:
  enabled: true
  fsGroup: 1001

securityContext: {}

containerSecurityContext:
  enabled: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 5
  successThreshold: 1

extraVolumeMounts: []

extraVolumes: []

sidecars: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

nodeAffinityPreset:
  type: ""
  key: ""
  values: []

containerPorts:
  sbi: 7777

startupProbe:
  enabled: false
  initialDelaySeconds: 600
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1