apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs.fullname" . }}-amf
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: amf
spec:
  ports:
  - name: sbi
    port: 7777
    protocol: TCP
  - name: ngap 
    port: 38412
    protocol: UDP

  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "open5gs.name" . }}
    app.kubernetes.io/component: amf
    app.kubernetes.io/instance: {{ .Release.Name }}
