apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-hss-diameter
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/component: hss
data:
  diameter-hss.conf: |-
{{ tpl (.Files.Get "resources/config/diameter-hss.conf") . | indent 4 }}