apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-hss
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/component: hss
data:
  hss.yaml: |
{{ tpl (.Files.Get "resources/config/hss.yaml") . | indent 4 }}
