apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs.fullname" . }}-hss
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/component: hss
spec:
  ports:
  - name: s6a
    port: 3868
    protocol: SCTP
  # - name: s6a-sctp
  #   port: 3868
  #   protocol: SCTP
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "open5gs.name" . }}
    app.kubernetes.io/component: hss
    app.kubernetes.io/instance: {{ .Release.Name }}