apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "open5gs.fullname" . }}-hss
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: hss
spec:
  replicas: 1
  serviceName: {{ include "open5gs.fullname" . }}-hss
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "open5gs.name" . }}
      app.kubernetes.io/component: hss
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
     labels:
        app.kubernetes.io/name: {{ include "open5gs.name" . }}
        app.kubernetes.io/component: hss
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{ include "open5gs.imagePullSecrets" . | indent 6 }}
      #initContainers:
      #- name: init-certs
      #  image: {{ template "open5gs.image" . }}
      #  command:
      #  - /bin/sh
      #  - /init-certs.sh
      #  workingDir: /certs
      #  env:
      #  - name: CERT_CN
      #    value: {{ include "open5gs.name" . }}-hss
      #  volumeMounts:
      #  - name: init-certs
      #    mountPath: /init-certs.sh
      #    subPath: "init-certs.sh"
      #  - name: certs
      #    mountPath: /certs
      containers:
      - name: hss
        image: {{ template "open5gs.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["open5gs-hssd"]
        env:
        - name: DB_URI
          {{- if not .Values.db_uri }}
          value: mongodb://{{ .Release.Name }}-mongodb/open5gs
          {{- else }}
          value: {{ .Values.db_uri }}
          {{- end  }}
        ports:
        - name: s6a
          containerPort: 3868
          protocol: SCTP
        # livenessProbe:
        #   tcpSocket:
        #     port: s6a
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        #readinessProbe:
        #  tcpSocket:
        #    port: s6a
        #  initialDelaySeconds: 5
        #  periodSeconds: 10

        resources:
{{ toYaml .Values.hss.resources | indent 10 }}
        volumeMounts:
        - name: hss-config
          mountPath: /opt/open5gs/etc/open5gs/hss.yaml
          subPath: "hss.yaml"
        - name: hss-diameter-config
          mountPath: /opt/open5gs/etc/freeDiameter/hss.conf
          subPath: "diameter-hss.conf"
        #- name: certs
        #  mountPath: /certs
      volumes:
      #- name: certs
      #  emptyDir: {}
      - name: hss-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-hss
      - name: hss-diameter-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-hss-diameter
      #- name: init-certs
      #  configMap:
      #    name: {{ include "open5gs.fullname" . }}-init-certs
