apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-init-certs
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/name: {{ include "open5gs.name" . }}
data:
  init-certs.sh: |
{{ tpl (.Files.Get "resources/config/init-certs.sh") . | indent 4 }}
