apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-mme
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/component: mme
data:
  mme.yaml: |
{{ tpl (.Files.Get "resources/config/mme.yaml") . | indent 4 }}
