apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs.fullname" . }}-mme
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: mme
spec:
  ports:
  - name: s1ap
    port: 36412
    protocol: SCTP
  - name: s6a
    port: 3868
    protocol: TCP
  - name: gtp-c
    port: 2123
    protocol: UDP
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "open5gs.name" . }}
    app.kubernetes.io/component: mme
    app.kubernetes.io/instance: {{ .Release.Name }}
