apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "open5gs.fullname" . }}-mme
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: mme
spec:
  replicas: 1
  serviceName: {{ include "open5gs.fullname" . }}-mme
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "open5gs.name" . }}
      app.kubernetes.io/component: mme
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
     labels:
        app.kubernetes.io/name: {{ include "open5gs.name" . }}
        app.kubernetes.io/component: mme
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{- include "open5gs.imagePullSecrets" . | indent 6 }}
      containers:
      - name: mme
        image: {{ template "open5gs.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["open5gs-mmed"]
        ports:
        - name: s6a
          containerPort: 3868
          protocol: TCP
        # livenessProbe:
        #   tcpSocket:
        #     port: s6a
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   tcpSocket:
        #     port: s6a
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        resources:
{{ toYaml .Values.mme.resources | indent 10 }}
        volumeMounts:
        - name: mme-config
          mountPath: /opt/open5gs/etc/open5gs/mme.yaml
          subPath: "mme.yaml"
        - name: mme-diameter-config
          mountPath: /opt/open5gs/etc/freeDiameter/mme.conf
          subPath: "diameter-mme.conf"
      volumes:
      - name: mme-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-mme
      - name: mme-diameter-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-mme-diameter
