apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-nrf
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: nrf
data:
  nrf.yaml: |
{{ tpl (.Files.Get "resources/config/nrf.yaml") . | indent 4 }}
