apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "open5gs.fullname" . }}-pcrf
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: pcrf
spec:
  replicas: 1
  serviceName: {{ include "open5gs.name" . }}-pcrf
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "open5gs.name" . }}
      app.kubernetes.io/component: pcrf
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
     labels:
        app.kubernetes.io/name: {{ include "open5gs.name" . }}
        app.kubernetes.io/component: pcrf
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{ include "open5gs.imagePullSecrets" . | indent 6 }}
      containers:
      - name: pcrf
        image: {{ template "open5gs.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["open5gs-pcrfd"]
        env:
        - name: DB_URI
          {{- if not .Values.db_uri }}
          value: mongodb://{{ .Release.Name }}-mongodb/open5gs
          {{- else }}
          value: {{ .Values.db_uri }}
          {{- end  }}
        ports:
        - name: gx
          containerPort: 3868
          protocol: SCTP
        # livenessProbe:
        #   tcpSocket:
        #     port: gx
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   tcpSocket:
        #     port: gx
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        resources:
{{ toYaml .Values.pcrf.resources | indent 10 }}
        volumeMounts:
        - name: pcrf-config
          mountPath: /opt/open5gs/etc/open5gs/pcrf.yaml
          subPath: "pcrf.yaml"
        - name: pcrf-diameter-config
          mountPath: /opt/open5gs/etc/freeDiameter/pcrf.conf
          subPath: "diameter-pcrf.conf"
      volumes:
      - name: pcrf-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-pcrf
      - name: pcrf-diameter-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-pcrf-diameter
