apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-pcrf-diameter
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/component: pcrf
data:
  diameter-pcrf.conf: |-
{{ tpl (.Files.Get "resources/config/diameter-pcrf.conf") . | indent 4 }}