{{- if .Values.imageCredentials }}
{{- if .Values.imageCredentials.registry }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "open5gs.fullname" . }}-registry
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "open5gs.dockerconfig" . }}
{{- end }}
{{- end }}