apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs.fullname" . }}-sgwc
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: sgwc
spec:
  ports:
  - name: gtp-c
    port: 2123
    protocol: UDP
  - name: pfcp
    port: 8805
    protocol: UDP

  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "open5gs.name" . }}
    app.kubernetes.io/component: sgwc
    app.kubernetes.io/instance: {{ .Release.Name }}
