apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "open5gs.fullname" . }}-sgwc
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: sgwc
spec:
  replicas: 1
  serviceName: {{ include "open5gs.fullname" . }}-sgwc
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "open5gs.name" . }}
      app.kubernetes.io/component: sgwc
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
     labels:
        app.kubernetes.io/name: {{ include "open5gs.name" . }}
        app.kubernetes.io/component: sgwc
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{ include "open5gs.imagePullSecrets" . | indent 6 }}
      containers:
      - name: sgwc
        image: {{ template "open5gs.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["open5gs-sgwcd"]
        ports:
        - name: gtp-c
          containerPort: 2123
          protocol: UDP
        - name: pfcp
          containerPort: 8805
          protocol: UDP
        # livenessProbe:
        #   tcpSocket:
        #     port: pfcp
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   tcpSocket:
        #     port: pfcp
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        resources:
{{ toYaml .Values.sgwc.resources | indent 10 }}
        volumeMounts:
        - name: sgwc-config
          mountPath:  /opt/open5gs/etc/open5gs/sgwc.yaml
          subPath: "sgwc.yaml"
      volumes:
      - name: sgwc-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-sgwc
