apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs.fullname" . }}-sgwu
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/component: sgwu
spec:
  clusterIP: None
  # ports:
  # - name: gtp-u
  #   port: 2152
  #   protocol: UDP
  # - name: pfcp
  #   port: 8805
  #   protocol: UDP  
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "open5gs.name" . }}
    app.kubernetes.io/component: sgwu
    app.kubernetes.io/instance: {{ .Release.Name }}