apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-smf
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: smf
data:
  smf.yaml: |
{{ tpl (.Files.Get "resources/config/smf.yaml") . | indent 4 }}
