apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs.fullname" . }}-smf
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/component: smf
spec:
  ports:
  - name: gtp-c
    port: 2123
    protocol: UDP
  - name: pfcp
    port: 8805
    protocol: UDP
  - name: s6a
    port: 3868
    protocol: SCTP
  - name: sbi
    port: 7777
    protocol: TCP

  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "open5gs.name" . }}
    app.kubernetes.io/component: smf
    app.kubernetes.io/instance: {{ .Release.Name }}