apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-smf-diameter
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: smf
data:
  diameter-smf.conf: |-
{{ tpl (.Files.Get "resources/config/diameter-smf.conf") . | indent 4 }}
