apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-udm
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: udm
data:
  udm.yaml: |
{{ tpl (.Files.Get "resources/config/udm.yaml") . | indent 4 }}
