apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs.fullname" . }}-udr
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: udr
spec:
  ports:
  - name: sbi
    port: 7777
    protocol: TCP

  selector:
    app.kubernetes.io/name: {{ include "open5gs.name" . }}
    app.kubernetes.io/component: udr
    app.kubernetes.io/instance: {{ .Release.Name }}
