apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-udr
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: udr
data:
  udr.yaml: |
{{ tpl (.Files.Get "resources/config/udr.yaml") . | indent 4 }}
