apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-udr
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: udr
spec:
  ports:
  - name: sbi
    port: 7777
    protocol: TCP

  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: udr
