apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "open5gs.fullname" . }}-udr
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: udr
spec:
  replicas: 1
  serviceName: {{ include "open5gs.fullname" . }}-udr
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "open5gs.name" . }}
      app.kubernetes.io/component: udr
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
     labels:
        app.kubernetes.io/name: {{ include "open5gs.name" . }}
        app.kubernetes.io/component: udr
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{ include "open5gs.imagePullSecrets" . | indent 6 }}
      containers:
      - name: udr
        image: {{ template "open5gs.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["open5gs-udrd"]
        env:
        - name: DB_URI
          {{- if not .Values.db_uri }}
          value: mongodb://{{ .Release.Name }}-mongodb/open5gs
          {{- else }}
          value: {{ .Values.db_uri }}
          {{- end  }}
        ports:
        - name: sbi
          containerPort: 7777
          protocol: TCP
        # livenessProbe:
        #   tcpSocket:
        #     port: s6a
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   tcpSocket:
        #     port: s6a
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        resources:
{{ toYaml .Values.udr.resources | indent 10 }}
        volumeMounts:
        - name: udr-config
          mountPath:  /opt/open5gs/etc/open5gs/udr.yaml
          subPath: "udr.yaml"
      volumes:
      - name: udr-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-udr

