apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-upf
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: upf
data:
  upf.yaml: |
{{ tpl (.Files.Get "resources/config/upf.yaml") . | indent 4 }}
