{{- if .Values.webui.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "open5gs.fullname" . }}-webui
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/component: webui
  annotations:
    {{- with .Values.webui.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  rules:
    {{- if .Values.webui.ingress.hostname }}
    - host: {{ .Values.webui.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.webui.ingress.path }}
            pathType: {{ .Values.webui.ingress.pathType }}
            backend: 
              service:
                name: {{ include "open5gs.fullname" $ }}-webui
                port: 
                  name: http
    {{- end }}
  {{- if .Values.webui.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.webui.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.webui.ingress.hostname }}
  {{- end }}

{{- end }}