apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open5gs.fullname" . }}-webui
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: webui
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "open5gs.name" . }}
      app.kubernetes.io/component: webui
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "open5gs.name" . }}
        app.kubernetes.io/component: webui
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{ include "open5gs.imagePullSecrets" . | indent 6 }}
      containers:
      - name: webui
        image: {{ template "open5gs.webui.image" . }}
        imagePullPolicy: {{ .Values.webui.image.pullPolicy | quote }}
        env:
        - name: DB_URI
          {{- if not .Values.db_uri }}
          value: mongodb://{{ .Release.Name }}-mongodb/open5gs
          {{- else }}
          value:  {{ .Values.db_uri }}
          {{- end  }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /                                                   
            port: http
          initialDelaySeconds: 120
          periodSeconds: 30
        resources:
{{ toYaml .Values.webui.resources | indent 10 }}
      terminationGracePeriodSeconds: 30
