{{ $open5gsName := ternary .Release.Name (printf "%s-open5gs" .Release.Name) (contains "open5gs" .Release.Name) }}

logger:
  level: {{ .Values.config.logLevel }}
parameter: {}

sgwc:
  pfcp:
    - addr:
        - "0.0.0.0"
      port: {{ .Values.containerPorts.pfcp }}
  gtpc:
    - addr:
        - "0.0.0.0"
      port: {{ .Values.containerPorts.gtpc }}
sgwu:
  pfcp:
    {{- range .Values.config.sgwu.pfcpList }}
    - name: {{ default (printf "%s-sgwu-pfcp" $open5gsName) .hostname }}
      port: {{ .port }}
      apn: {{ .apn }}
    {{- end }}
