image:
  registry: docker.io
  repository: openverso/srs-lte
  tag: "20_04_1"
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #  - regcred

ue:
  opc: '63bfa50ee6523365ff14c1f45f88737d'
  k: '00112233445566778899aabbccddeeff'
  imsi: '001010123456789'
  imei: '353490069873319'
  enb: enb
  resources: {}

enb:
  mcc: '001'
  mnc: '01'
  tac: '0001'
  mme: mme
  ue: ue
  resources: {}
