apiVersion: v1
appVersion: "2.0.18"
description: >
  Helm chart to deploy Open5gs services on Kubernetes.
home: https://github.com/gradiant/openverso-charts
sources:
  - http://open5gs.org
icon: https://open5gs.org/assets/img/open5gs_logo.png
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
  url: https://gradiant.org
name: open5gs
version: 0.1.0
keywords:
  - epc
  - ngc
