apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-pcrf
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/component: pcrf
data:
  pcrf.yaml: |
{{ tpl (.Files.Get "resources/config/pcrf.yaml") . | indent 4 }}
