apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs.fullname" . }}-pgw
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: pgw
spec:
  ports:
  - name: gx
    port: 3868
    protocol: TCP
  - name: gx-sctp
    port: 3868
    protocol: SCTP
  - name: gtp-c
    port: 2123
    protocol: UDP
  - name: gtp-u
    port: 2152
    protocol: UDP  
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "open5gs.name" . }}
    app.kubernetes.io/component: pgw
    app.kubernetes.io/instance: {{ .Release.Name }}