apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs.fullname" . }}-pgw
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/component: pgw
data:
  pgw.yaml: |
{{ tpl (.Files.Get "resources/config/pgw.yaml") . | indent 4 }}
