apiVersion: v1
kind: Service
metadata:
  name: {{ include "open5gs.fullname" . }}-webui
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}  
    app.kubernetes.io/component: webui
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "open5gs.name" . }}
    app.kubernetes.io/component: webui
    app.kubernetes.io/instance: {{ .Release.Name }}