logger:
{{ toYaml .Values.ausf.logger | indent 2 }}

{{- if .Values.ausf.parameter }}
parameter:
{{ toYaml .Values.ausf.parameter | indent 2 }}
{{- end }}

#
ausf:
    sbi:
      dev: eth0

nrf:
    sbi:
      - name: "{{ include "open5gs.fullname" . }}-nrf"
