logger:
{{ toYaml .Values.sgwu.logger | indent 2 }}
{{- if .Values.sgwu.parameter }}
parameter:
{{ toYaml .Values.sgwu.parameter | indent 2 }}
{{- end }}

{{- if .Values.sgwu.max }}
max:
{{ toYaml .Values.sgwu.max | indent 2 }}
{{- end }}

{{- if .Values.sgwu.pool }}
pool:
{{ toYaml .Values.sgwu.pool | indent 2 }}
{{- end }}

sgwu:
  gtpu:
    dev: eth0
    {{- if .Values.sgwu.externalService.enabled }}
    {{- if .Values.sgwu.externalService.advertise }}
    advertise: {{ .Values.sgwu.advertise }}
    {{- else }}
    advertise: {{ include "common.names.fullname" . }}-sgwu-ext.{{ .Release.Namespace }}.{{ .Values.sgwu.externalService.advertiseDomain }}
    {{- end }}
    {{- end }}
  pfcp:
    dev: eth0

sgwc:
  pfcp:
    - name: "{{ include "common.names.fullname" . }}-sgwc"
