logger:
    file: /var/log/open5gs/smf.log
{{ toYaml .Values.mme.logger | indent 2 }}

{{- if .Values.mme.parameter }}
parameter:
{{ toYaml .Values.mme.parameter | indent 2 }}
{{- end }}

smf:
  freeDiameter: diameter-smf.conf
  sbi:
    dev: eth0
  gtpc:
    dev: eth0
  pfcp:
    dev: eth0
  pdn:
    - addr: {{ .Values.smf.pdn.addr }}
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400

nrf:
    sbi:
      - name: "{{ include "open5gs.fullname" . }}-nrf"

upf:
    pfcp:
      - name: "{{ include "open5gs.fullname" . }}-upf"
