db_uri:  {{ tpl .Values.udr.db_uri . }}

logger:
  level: {{ .Values.udr.config.logLevel }}
parameter: {}

nrf:
  sbi:
    - name: "{{ include "common.names.fullname" . }}-nrf"
      port: 7777

udr:
  sbi:
    dev: eth0
    port: 7777
