logger:
{{ toYaml .Values.upf.logger | indent 2 }}
{{- if .Values.upf.parameter }}
parameter:
{{ toYaml .Values.upf.parameter | indent 2 }}
{{- end }}

upf:
    pfcp:
      dev: eth0
    gtpu:
      dev: {{ .Values.upf.dev }}
      {{- if .Values.upf.externalService.enabled }}
      {{- if .Values.upf.externalService.advertise }}
      advertise: {{ .Values.upf.externalService.advertise }}
      {{- else }}
      advertise: {{ include "common.names.fullname" . }}-upf-ext.{{ .Release.Namespace }}.{{ .Values.upf.externalService.advertiseDomain }}
      {{- end }}
      {{- end }}
    subnet:
      - addr: {{ .Values.upf.pdn.addr }}

smf:
    pfcp:
      - name: "{{ include "common.names.fullname" . }}-smf"
