logger:
    file: /var/log/open5gs/ausf.log
    {{ toYaml .Values.mme.logger | indent 2 }}

    {{- if .Values.mme.parameter }}
    parameter:
    {{ toYaml .Values.mme.parameter | indent 2 }}
    {{- end }}

#
ausf:
    sbi:
      dev: eth0

nrf:
    sbi:
      - name: "{{ include "open5gs.fullname" . }}-nrf"
